#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    workout-app-phpmyadmin-80-http:
      entrypoints:
        - http-8036
      rule: HostRegexp(`^workout-app\.ddev\.site$`)
      
      service: "workout-app-phpmyadmin-80"
      tls: false
      # middlewares:
      #   - "workout-app-redirectHttps"
    workout-app-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^workout-app\.ddev\.site$`)
      
      service: "workout-app-web-80"
      tls: false
      # middlewares:
      #   - "workout-app-redirectHttps"
    workout-app-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^workout-app\.ddev\.site$`)
      
      service: "workout-app-web-8025"
      tls: false
      # middlewares:
      #   - "workout-app-redirectHttps"
    workout-app-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^workout-app\.ddev\.site$`)
      
      service: "workout-app-xhgui-80"
      tls: false
      # middlewares:
      #   - "workout-app-redirectHttps"
    
    
    workout-app-phpmyadmin-80-https:
      entrypoints:
        - http-8037
      rule: HostRegexp(`^workout-app\.ddev\.site$`)
      
      service: "workout-app-phpmyadmin-80"
      
      tls: true
      
    
    
    workout-app-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^workout-app\.ddev\.site$`)
      
      service: "workout-app-web-80"
      
      tls: true
      
    workout-app-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^workout-app\.ddev\.site$`)
      
      service: "workout-app-web-8025"
      
      tls: true
      
    
    workout-app-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^workout-app\.ddev\.site$`)
      
      service: "workout-app-xhgui-80"
      
      tls: true
      
    

  middlewares:
    workout-app-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    workout-app-phpmyadmin-80:
      loadbalancer:
        servers:
          - url: http://ddev-workout-app-phpmyadmin:80
        
    
    workout-app-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-workout-app-web:80
        
    workout-app-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-workout-app-web:8025
        
    
    
    workout-app-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-workout-app-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/workout-app.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/workout-app.key